version: '3.9'

services:
  sentinel:
    build: .
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    environment:
      - OLLAMA_HOST=http://localhost:11434
    restart: always

volumes:
  ollama:
